# Generated by Django 3.2.16 on 2023-02-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_step_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(default='img/dish.svg', upload_to='images'),
            preserve_default=False,
        ),
    ]
