# Generated by Django 3.2.16 on 2023-03-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
