# Generated by Django 3.2.16 on 2023-08-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_step_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
